# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20161208_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.Location', verbose_name='\u843d\u5730'),
        ),
        migrations.AlterField(
            model_name='event',
            name='nums',
            field=models.IntegerField(verbose_name='\u53c2\u4e0e\u4eba\u6570'),
        ),
        migrations.AlterField(
            model_name='event',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.Project', verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='subproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='projects.SubProject', verbose_name='\u5b50\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='event',
            name='time',
            field=models.DateTimeField(verbose_name='\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=50, verbose_name='\u6807\u9898'),
        ),
    ]
