# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20161208_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletype',
            name='article_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u5206\u7c7b'),
        ),
        migrations.AlterField(
            model_name='articletype',
            name='introduction',
            field=models.CharField(default='\u6682\u65e0\u7b80\u4ecb', max_length=100, verbose_name='\u7b80\u4ecb'),
        ),
    ]
