# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='article_type',
        ),
        migrations.RemoveField(
            model_name='article',
            name='project',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.RemoveField(
            model_name='event',
            name='project',
        ),
        migrations.RemoveField(
            model_name='event',
            name='subproject',
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='ArticleType',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
    ]
