# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20161208_2127'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name_plural': '\u843d\u5730'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name_plural': '\u9879\u76ee'},
        ),
        migrations.AlterModelOptions(
            name='servicetype',
            options={'verbose_name_plural': '\u670d\u52a1\u7c7b\u578b'},
        ),
        migrations.AlterModelOptions(
            name='subproject',
            options={'verbose_name_plural': '\u5b50\u9879\u76ee'},
        ),
    ]
