# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-08 14:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20161208_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetype',
            name='introduction',
            field=models.CharField(default='\u6682\u65e0\u7b80\u4ecb', max_length=100, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AddField(
            model_name='subproject',
            name='introduction',
            field=models.CharField(default='\u6682\u65e0\u7b80\u4ecb', max_length=100, verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u843d\u5730\u5c45\u59d4'),
        ),
        migrations.AlterField(
            model_name='location',
            name='region',
            field=models.CharField(max_length=50, verbose_name='\u6240\u5c5e\u8857\u9053'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_time',
            field=models.DateField(verbose_name='\u7ed3\u9879\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='introduction',
            field=models.TextField(verbose_name='\u7b80\u4ecb'),
        ),
        migrations.AlterField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(related_name='projects', to='projects.Location', verbose_name='\u843d\u5730'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='project',
            name='service_types',
            field=models.ManyToManyField(related_name='projects', to='projects.ServiceType', verbose_name='\u670d\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_time',
            field=models.DateField(verbose_name='\u8d77\u59cb\u65f6\u95f4'),
        ),
        migrations.AlterField(
            model_name='project',
            name='subprojects',
            field=models.ManyToManyField(related_name='projects', to='projects.SubProject', verbose_name='\u5b50\u9879\u76ee'),
        ),
        migrations.AlterField(
            model_name='servicetype',
            name='service_type',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u670d\u52a1\u7c7b\u578b'),
        ),
        migrations.AlterField(
            model_name='subproject',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='\u5b50\u9879\u76ee'),
        ),
    ]
