# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='subproject',
        ),
        migrations.AddField(
            model_name='project',
            name='subprojects',
            field=models.ManyToManyField(default=None, related_name='projects', to='blog.SubProject'),
        ),
    ]
