# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20161207_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='subprojects',
            field=models.ManyToManyField(related_name='projects', to='blog.SubProject'),
        ),
    ]
